image: debian/stable
packages:
  - git 
  - wget 
  - flex 
  - bison 
  - gperf 
  - python3 
  - python3-pip 
  - python3-venv 
  - cmake 
  - ninja-build 
  - ccache 
  - libffi-dev 
  - libssl-dev 
  - dfu-util 
  - libusb-1.0-0
sources:
  - https://git.sr.ht/~truita/esp-mpu9250
  - https://github.com/espressif/esp-idf.git#v5.2.1
tasks:
  - setup: |
      cd esp-idf/
      ./install.sh
  - build: |
      source esp-idf/export.sh
      cd esp-mpu9250/example
      idf.py build
